name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & Unit Tests
        run: mvn clean test -q

      - name: Run Selenium Tests
        run: |
          chmod +x ./chromedriver
          mvn -Dtest=UsuarioFlowTest test -q

  performance:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Install JMeter
        run: sudo apt-get update && sudo apt-get install -y jmeter
      - name: Run JMeter Load Test
        run: jmeter -n -t performance/HealthTrackPlan.jmx -l performance/resultados.jtl

  quality:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: your-org_healthtrack
          organization: your-org
          token: ${{ secrets.SONAR_TOKEN }}
